version: '3.7'

services:

  event-store:
    build:
      context: .
    image: localhost:5000/event-store
    environment:
      - KAFKA_BOOTSTRAP_SERVERS="kafka1:19092,kafka2:19092,kafka3:19092"
      - KAFKA_TOPIC="events"
      - KAFKA_GROUP_ID="event_store"
#      - DATABASE_URL=postgressql://event_user:event_pwd@docker01:55432/events
      - DATABASE_URL=postgres://event_user:event_pwd@event-db:5432/events
    networks:
      - kafka
      - event-db

networks:
  kafka:
    external: true
  event-db:
    external: true
